/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.sistema_gestao.views;

import br.senai.sc.sisgestao.dao.EquipeDao;

/**
 *
 * @author Aluno
 */
public class CadastroEquipe extends javax.swing.JPanel {
    EquipeDao con1 = new EquipeDao();
    /**
     * Creates new form CadastroEquipe
     */
    public CadastroEquipe() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2CadUsu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CPNomeEquipe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areatextDescricaoEquipe = new javax.swing.JTextArea();
        botaoSalvarEquipe = new javax.swing.JButton();

        jLabel2CadUsu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2CadUsu.setText("CADASTRO DE EQUIPE");

        jLabel1.setText("NOME EQUIPE ");

        jLabel2.setText("DESCRIÇÃO EQUIPE");

        areatextDescricaoEquipe.setColumns(20);
        areatextDescricaoEquipe.setRows(5);
        jScrollPane1.setViewportView(areatextDescricaoEquipe);

        botaoSalvarEquipe.setText("Salvar ");
        botaoSalvarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarEquipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2CadUsu))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(CPNomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoSalvarEquipe)
                .addGap(194, 194, 194))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2CadUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CPNomeEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(botaoSalvarEquipe)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarEquipeActionPerformed
        // TODO add your handling code here:
        CadastroEquipe cadEquipe = new CadastroEquipe();
        
        String nome = CPNomeEquipe.getText();
        String descricao = areatextDescricaoEquipe.getText();
        
        
     
        
    }//GEN-LAST:event_botaoSalvarEquipeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPNomeEquipe;
    private javax.swing.JTextArea areatextDescricaoEquipe;
    private javax.swing.JButton botaoSalvarEquipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2CadUsu;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
